### PR TITLE
Made responsive for tablets 

### PR DESCRIPTION
**Pull request by Utsab5**
I have fixed some problems and made the website responsive for tablets. I am facing some problems while making it responsive for mobile devices. (issue #5 )

### CODE REVIEW

**Comment by Utsab5** [comment]
I have done it.
You can check it now.

**Comment by anand-3399** [comment]
> I have done it. You can check it now.

Can you share me the link of your GitHub pages???

**Comment by Utsab5** [comment]
https://github.com/Utsab5/Hactoberfest-Windows11/deployments/activity_log?environment=github-pages

**Comment by anand-3399** [comment]
> https://github.com/Utsab5/Hactoberfest-Windows11/deployments/activity_log?environment=github-pages

I appreciate your effort but I am sorry to say that I cannot merge your Pull request, as there are certain bugs that need to be fixed before merging your Efforts.

**Comment by anand-3399** [comment]
> > https://github.com/Utsab5/Hactoberfest-Windows11/deployments/activity_log?environment=github-pages
> 
> I appreciate your effort but I am sorry to say that I cannot merge your Pull request, as there are certain bugs that need to be fixed before merging your Efforts.

We can discuss your changes on the discussion section.

**Comment by anand-3399** [comment]
> > > https://github.com/Utsab5/Hactoberfest-Windows11/deployments/activity_log?environment=github-pages
> > 
> > 
> > I appreciate your effort but I am sorry to say that I cannot merge your Pull request, as there are certain bugs that need to be fixed before merging your Efforts.
> 
> We can discuss your changes on the discussion section.

Just send your doubts in https://github.com/anand-3399/Hactoberfest-Windows11/discussions/6 discussion section.
I would be happy to help.

**Comment by anand-3399** [comment]
@Utsab5 I have seen your changes made and really appreciate it.
**Hence I am giving you an opportunity to resubmit your Pull Request and complete your Pull Requests.**
1. Delete your forked repository
2. Once again fork this repository **after deleting it**.
3. Add two to three desktop icons of applications.
4. You can add Netflix app, Discord app, etc on the start menu
5. Pull request you changes.

**Pull request closed without merging**
