### PR TITLE
added the start all apps page

### PR DESCRIPTION
**Pull request by MAVERICK-VF142**
done! please add hacktoberfest-accepted

### CODE REVIEW

**Comment by anand-3399** [comment]
> done! please add hacktoberfest-accepted

@MAVERICK-VF142 Can you can you switch on GitHub Pages on your forked repository so that I can See the changes you made?

**Comment by MAVERICK-VF142** [comment]
https://github.com/MAVERICK-VF142/Hactoberfest-Windows11.git
try to clone it and see

**Comment by MAVERICK-VF142** [comment]
how to do it

**Comment by anand-3399** [comment]
> how to do it @anand-3399

Go to Your forked repository settings. 
Go to Pages
Then **Branch** Select **main**

image

**Comment by MAVERICK-VF142** [comment]
https://maverick-vf142.github.io/Hactoberfest-Windows11/allapps.html
here yo go

**Comment by anand-3399** [comment]
@MAVERICK-VF142 Soryy to say you that I cannot merge your Pull request.

**Comment by anand-3399** [comment]
You have not implemented **DRY** principle
Its simply is **DO NOT REPEAT YOURSELF**. 

For every feature if we are designing a new Page then if is definitely not be working

**Pull request closed without merging**
