### PR TITLE
Date Time Menu

### PR DESCRIPTION
**Pull request by dilipsuthar1999**
I Created Date and Notification Menu

image

### CODE REVIEW

**Comment by anand-3399** [comment]
> I Created Date and Notification Menu
> 
> image

Great contribution.
but can you toggle on the GitHub pages on your forked repository so that I can visualize your work done???

**Comment by anand-3399** [comment]
> > I Created Date and Notification Menu
> > image
> 
> Great contribution. but can you toggle on the GitHub pages on your forked repository so that I can visualize your work done???

https://github.com/anand-3399/Hactoberfest-Windows11/discussions/6#discussioncomment-3872587
Just see to it to toggle GitHub pages

**Comment by dilipsuthar1999** [comment]
Can you guide me. I come up with this page
image

**Comment by anand-3399** [comment]
> Can you guide me. I come up with this page
> image
> 

Goto pages section.
This is below Environments.

**Comment by anand-3399** [comment]
> > Can you guide me. I come up with this page
> > image
> > 
> 
> Goto pages section.
> This is below Environments.

Then **Branch** Select **main**.

**Comment by dilipsuthar1999** [comment]
Thanks @anand-3399 
URL - https://dilipsuthar1999.github.io/Hactoberfest-Windows11/

**Comment by anand-3399** [comment]
### Amazing contribution @dilipsuthar1999 
Really amazing work you have done.
You are the **STAR PERFORMER** in this project.

Screenshot (56)

Although there are some of the CSS errors but I can fix it as it is minor errors.

**Pull request merged**
